[build]
  command = "npm run build"
  publish = ".next"
  # Les validations passent par GitHub Actions. Une publication Netlify se fait manuellement.
  ignore = "true"

[build.environment]
  NODE_VERSION = "22"

[context.production]
  command = "npm run build"

[context.production.environment]
  APP_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  framework = "#auto"
